"Practical Machine Learning" Course project

### Introduction
(For a more detailed introduction, see the README)

```{r download}
if(file.exists("data/pml-training.csv")) {
    print("File already downloaded")
} else {
    trainingURL <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
    download.file(trainingURL, "data/pml-training.csv")
}

if(file.exists("data/pml-testing.csv")) {
    print("File already downloaded")
} else {
testingURL <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(testingURL, "data/pml-testing.csv")
}

library(caret)
```
```{r}
train.data <- read.csv("data/pml-training.csv")
train.data[train.data==""] <- NA
train.data[train.data=="#DIV/0!"] <- NA
na.rows <- apply(train.data, 1, function(x){sum(is.na(x))})
na.rm.index <- which(is.na(train.data[1,]))
train.data <- train.data[, -na.rm.index]
```
In order to evaluate our model before submitting it for grading, we'll designate a partition of it for validation
```{r}
set.seed(12345)
inTrain <- createDataPartition(y=train.data$classe,p=0.7, list=FALSE) 
train.data.train <- train.data[inTrain,]
train.data.test <- train.data[-inTrain,]
```
```{r, cache=TRUE}
set.seed(12345)
modFit <- train(classe ~ ., data=train.data.train[,8:60], method="rf", prox=TRUE) 
```
```{r}
save(modFit, file = "mod2.rda")
pred.train <- predict(modFit, train.data.train)
train.data.train$predRight <- pred.train==train.data.train$classe
table(pred.train, train.data.train$classe)
pred.test <- predict(modFit,train.data.test)
train.data.test$predRight <- pred.test==train.data.test$classe
table(pred.test,train.data.test$classe)
```
```{r}
sum(train.data.test$predRight)/nrow(train.data.test)
```
Apply the model to the testing set and export the `.txt` files
```{r}
setwd("data")
test.data <- read.csv("pml-testing.csv")
test.data[test.data==""] <- NA
test.data[test.data=="#DIV/0!"] <- NA
test.data <- test.data[, -na.rm.index]
answers = predict(modFit, test.data)
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
pml_write_files(answers)
```


